/**
 * Shared-pool avatar URL helper. Renders are pre-generated by
 * `scripts/generate-avatar-pool.ts` into `/public/avatars/pool/{0..N-1}.svg`,
 * so this module just hashes the user id into a slot — no SVG generation,
 * no React, runs anywhere (server components, client components, scripts).
 *
 * Collisions are by design: with POOL_SIZE = 5000, two users will only
 * occasionally share an avatar, and that's OK because the alternative
 * (boring-avatars at request time) doesn't work in Next.js's RSC bundle.
 */

export const POOL_SIZE = 5000

// DJB2 — small deterministic hash that gives the same bucket on server and
// client without needing Web Crypto / node:crypto. Same algorithm as
// pickAvatarConfig() in boring-avatar.ts so we don't accidentally couple
// browsers to a Node-only digest.
function djb2(input: string): number {
  let h = 5381
  for (let i = 0; i < input.length; i++) {
    h = (h * 33) ^ input.charCodeAt(i)
  }
  return h >>> 0
}

/**
 * Resolve a fallback avatar URL for a user that doesn't have a stored
 * `image`. Pure function — same userId always returns the same URL.
 */
export function poolAvatarUrl(userId: string): string {
  const slot = djb2(userId) % POOL_SIZE
  return `/avatars/pool/${slot}.svg`
}
